using System;
using System.ComponentModel;
using UnityEngine;

namespace Unity.AI.Toolkit.Compliance
{
    /// <summary>
    /// Legal related constants.
    /// </summary>
    static class Legal
    {
        /// <summary>
        /// The label used to mark assets generated by Unity AI.
        /// </summary>
        public const string UnityAIGeneratedLabel = "UnityAI";
    }
}
